Repository moDgo-OTT/moDgo, pull requests merged in 2021-11, with the labels that each got.

#2 Project intial settings
  back/.gitignore
  back/.idea/.gitignore
  back/.idea/.name
  back/.idea/compiler.xml
  back/.idea/dbnavigator.xml
  back/.idea/gradle.xml
  back/.idea/jarRepositories.xml
  back/.idea/libraries-with-intellij-classes.xml
  back/.idea/misc.xml
  back/.idea/vcs.xml
  back/src/main/resources/application.properties
Labels: BackEnd

#8 feat:User Login implementation
  back/.idea/misc.xml
  back/src/main/java/org/moDgo/MoDgoApplication.java
  back/src/main/java/org/moDgo/controller/user/UserController.java
  back/src/main/java/org/moDgo/controller/user/UserCreateRequestDto.java
  back/src/main/java/org/moDgo/controller/user/UserResponseDto.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/domain/LikedClub.java
  back/src/main/java/org/moDgo/domain/Member.java
  back/src/main/java/org/moDgo/domain/User.java
  back/src/main/java/org/moDgo/repository/UserRepository.java
  back/src/main/java/org/moDgo/service/UserService.java
  back/src/main/resources/application.yml
Labels: BackEnd

#9 feat:Domain package class 생성
  back/src/main/java/org/moDgo/domain/BaseTime.java
  back/src/main/java/org/moDgo/domain/ClubStatus.java
  back/src/main/java/org/moDgo/domain/Comment.java
  back/src/main/java/org/moDgo/domain/EvaluationStatus.java
Labels: BackEnd

#12 feat: Google Login(FE)
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/common/navBar/login/Login.jsx
  front/src/images/icons/add.png
  front/src/images/icons/comments.png
  front/src/images/icons/filled_heart.png
  front/src/images/icons/google.png
  front/src/images/icons/logo.png
  front/src/images/icons/profile.png
  front/src/images/icons/search.png
  front/src/images/icons/subject.png
  front/src/images/icons/trash.png
  front/src/images/icons/unfilled_heart.png
Labels: FrontEnd

#14 feat:CORS를 위한 WebConfig 추가
  back/src/main/java/org/moDgo/config/WebConfig.java
  front/yarn.lock
Labels: BackEnd

#18 배너이미지추가
  front/src/images/disneyplus.png
  front/src/images/netflix.png
  front/src/images/watchaplay.png
  front/src/images/wave.png
Labels: FrontEnd

#19 feat:Commnet,LikedClub Entity 설정
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237.xml
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/information_schema.FNRwLQ.zip
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/modgo.avszBg.meta
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/modigo.z3hLwA.meta
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/performance_schema.kIw0nw.meta
  back/.idea/dataSources/7ce6e3a0-83cb-432a-a47d-32a33e833237/storage_v2/_src_/schema/sys.zb4BAA.meta
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Club.class
  back/build/classes/java/main/org/moDgo/domain/LikedClub.class
  back/build/classes/java/main/org/moDgo/domain/Member.class
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/controller/club/ClubController.java
  back/src/main/java/org/moDgo/controller/club/ClubCreateRequestDto.java
  back/src/main/java/org/moDgo/domain/BaseTime.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/domain/Comment.java
  back/src/main/java/org/moDgo/domain/LikedClub.java
  back/src/main/java/org/moDgo/domain/Member.java
  back/src/main/java/org/moDgo/repository/ClubRepository.java
  back/src/main/java/org/moDgo/service/ClubService.java
  front/node_modules/.cache/.eslintcache
Labels: BackEnd

#24 feat:exception handling in preventing duplicated clubkind
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Club.class
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/common/Messages.java
  back/src/main/java/org/moDgo/common/error/ClubDuplicatedException.java
  back/src/main/java/org/moDgo/common/error/ClubNotFoundException.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/domain/ClubKind.java
  back/src/main/java/org/moDgo/domain/ClubStatus.java
  back/src/main/java/org/moDgo/repository/ClubRepository.java
  back/src/main/java/org/moDgo/service/ClubService.java
Labels: BackEnd

#25 feat:Club Detail 페이지 구현 및 Club Status 정리
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Club.class
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/controller/club/ClubController.java
  back/src/main/java/org/moDgo/controller/club/ClubDetailPageResponseDto.java
  back/src/main/java/org/moDgo/controller/club/ClubDetailResponseDto.java
  back/src/main/java/org/moDgo/controller/club/ClubPageResponseDto.java
  back/src/main/java/org/moDgo/controller/club/ClubResponseDto.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/domain/ClubStatus.java
  back/src/main/java/org/moDgo/repository/ClubRepository.java
  back/src/main/java/org/moDgo/service/ClubService.java
Labels: BackEnd

#28 Comment Controller& Service 추가
  .idea/workspace.xml
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.gradle/buildOutputCleanup/outputFiles.bin
  back/.idea/workspace.xml
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/common/Messages.java
  back/src/main/java/org/moDgo/common/error/CommentNotFoundException.java
  back/src/main/java/org/moDgo/controller/comment/CommentController.java
  back/src/main/java/org/moDgo/controller/comment/CommentCreateRequestDto.java
  back/src/main/java/org/moDgo/controller/comment/CommentPageResponseDto.java
  back/src/main/java/org/moDgo/controller/comment/CommentResponseDto.java
  back/src/main/java/org/moDgo/controller/comment/CommentUpdateRequestDto.java
  back/src/main/java/org/moDgo/domain/Comment.java
  back/src/main/java/org/moDgo/repository/CommentRepository.java
  back/src/main/java/org/moDgo/service/CommentService.java
Labels: BackEnd

#37 feat: MemberController
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/dbnavigator.xml
  back/.idea/workspace.xml
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/common/Messages.java
  back/src/main/java/org/moDgo/common/error/MemberNotFoundException.java
  back/src/main/java/org/moDgo/controller/member/MemberApproveRequestDto.java
  back/src/main/java/org/moDgo/controller/member/MemberController.java
  back/src/main/java/org/moDgo/controller/member/MemberCreateRequestDto.java
  back/src/main/java/org/moDgo/controller/member/MemberResponseDto.java
  back/src/main/java/org/moDgo/repository/MemberRepository.java
  back/src/main/java/org/moDgo/service/MemberService.java
  front/package.json
  front/src/components/common/navBar/login/Login.jsx
  front/yarn.lock
Labels: BackEnd

#41 fix:Club Create 생성 오류 수정
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/controller/club/ClubController.java
  back/src/main/java/org/moDgo/controller/club/ClubCreateRequestDto.java
  back/src/main/java/org/moDgo/domain/ClubKind.java
  back/src/main/java/org/moDgo/service/ClubService.java
  front/src/components/common/navBar/register/RegisterForm.jsx
Labels: BackEnd, FrontEnd

#42 fix: 태그 기능 수정
  front/src/components/board/TagFilter.jsx
  front/src/components/common/navBar/register/RegisterForm.jsx
Labels: FrontEnd

#43 fix: imgUrl OTT 태그별 사진 추가
  front/src/App.jsx
  front/src/components/board/ClubCard.jsx
  front/src/components/common/navBar/login/Login.jsx
  front/src/components/common/navBar/register/RegisterForm.jsx
  front/src/components/detail/Comment.jsx
  front/src/components/detail/Commnet.jsx
  front/src/components/detail/DetailInfo.jsx
  front/src/components/detail/InfoBox.jsx
  front/src/components/detail/Main.jsx
  front/src/components/myPage/EditForm.jsx
  front/src/components/myPage/JoinedClubCard.jsx
  front/src/components/myPage/LikedClubCard.jsx
  front/src/components/myPage/Main.jsx
  front/src/images/disneyplusCover.png
  front/src/images/netflixCover.png
  front/src/images/watchaCover.png
  front/src/images/wavveCover.png
  front/src/pages/Detail.js
  front/src/pages/Detail.jsx
  front/src/pages/MyPage.jsx
Labels: FrontEnd

#50 feat:Club update 기능 추가
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Club.class
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/controller/club/ClubController.java
  back/src/main/java/org/moDgo/controller/club/ClubUpdateRequestDto.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/service/ClubService.java
  back/src/main/resources/application.yml
Labels: BackEnd

#53 fix:Approval Status에 따른 멤버 get 요청 기능 수정
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Club.class
  back/build/classes/java/main/org/moDgo/domain/Member.class
  back/build/classes/java/main/org/moDgo/domain/User$UserBuilder.class
  back/build/classes/java/main/org/moDgo/domain/User.class
  back/build/resources/main/application.yml
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/config/WebConfig.java
  back/src/main/java/org/moDgo/controller/club/ClubController.java
  back/src/main/java/org/moDgo/controller/club/ClubResponseDto.java
  back/src/main/java/org/moDgo/controller/likedclub/LikedClubController.java
  back/src/main/java/org/moDgo/controller/member/MemberController.java
  back/src/main/java/org/moDgo/controller/member/MemberResponseDto.java
  back/src/main/java/org/moDgo/domain/Club.java
  back/src/main/java/org/moDgo/domain/Member.java
  back/src/main/java/org/moDgo/domain/User.java
  back/src/main/java/org/moDgo/service/MemberService.java
  back/src/main/resources/application.yml
  front/src/components/detail/InfoBox.jsx
  front/src/components/detail/Main.jsx
Labels: BackEnd

#63 fix: 마이페이지 모임관리
  front/src/components/detail/DetailInfo.jsx
  front/src/components/detail/InfoBox.jsx
  front/src/components/detail/Main.jsx
  front/src/components/myPage/EditForm.jsx
  front/src/components/myPage/Main.jsx
  front/src/components/myPage/MyClubCard.jsx
Labels: FrontEnd

#64 feat:Member Evaluation 기능 추가
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/classes/java/main/org/moDgo/domain/Member.class
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/common/Messages.java
  back/src/main/java/org/moDgo/common/error/EvaluationClearException.java
  back/src/main/java/org/moDgo/controller/member/MemberController.java
  back/src/main/java/org/moDgo/controller/member/MemberEvaluationRequestDto.java
  back/src/main/java/org/moDgo/domain/EvaluationKind.java
  back/src/main/java/org/moDgo/domain/Member.java
  back/src/main/java/org/moDgo/service/MemberService.java
  front/.env.production
  front/nohup.out
Labels: BackEnd

#65 feat: Member Evaluation score get
  back/.gradle/7.2/executionHistory/executionHistory.bin
  back/.gradle/7.2/executionHistory/executionHistory.lock
  back/.gradle/7.2/fileHashes/fileHashes.bin
  back/.gradle/7.2/fileHashes/fileHashes.lock
  back/.gradle/7.2/fileHashes/resourceHashesCache.bin
  back/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  back/.idea/workspace.xml
  back/build/tmp/compileJava/previous-compilation-data.bin
  back/src/main/java/org/moDgo/controller/member/MemberController.java
  back/src/main/java/org/moDgo/controller/member/MemberEvaluationResponseDto.java
Labels: BackEnd
